[metadata]
name = sentinel
version = 0.1.0
description = Sentinel self-hosted monitoring (editable install for development)
author = 
license = MIT

[options]
packages = find:
include_package_data = True
python_requires = >=3.8
install_requires =
	cryptography
	mac-vendor-lookup
	psycopg[binary]>=3.1
	scapy
	zeroconf
	discord.py>=2.0

[options.entry_points]
console_scripts =
	sentinel = scripts.sentinel:main
